service: serverless-crud

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "dynamodb:*"
          Resource: "arn:aws:dynamodb:us-east-1:934720402085:table/usersTable"

plugins:
  - serverless-offline
  - serverless-dynamodb-local

package:
  individually: true
  patterns:
    - "!*/**"
    - "!**"

functions:
  getUser:
    handler: src/getUser/handler.getUser
    events:
      - http:
          path: users/{id}
          method: GET
    package:
      patterns:
        - "src/getUser/handler.js"
  getUsers:
    handler: src/getUsers/handler.getUsers
    events:
      - http:
          path: users
          method: GET
    package:
      patterns:
        - "src/getUsers/handler.js"
  createUser:
    handler: src/createUser/handler.createUser
    events:
      - http:
          path: users
          method: POST
    package:
      patterns:
        - "src/createUser/handler.js"
  updateUser:
    handler: src/updateUser/handler.updateUser
    events:
      - http:
          path: users/{id}
          method: PATCH
    package:
      patterns:
        - "src/updateUser/handler.js"
  deleteUser:
    handler: src/deleteUser/handler.deleteUser
    events:
      - http:
          path: users/{id}
          method: DELETE
    package:
      patterns:
        - "src/deleteUser/handler.js"

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      # noStart: true     # Uncomment only if you already have a DynamoDB running locally
    seed:
      domain:
        sources:
          - table: usersTable
            sources: [./db/usersTable.json]

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
